config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "static_page#home"

  namespace :admin do
    resources :categories
    resources :lessons
    resources :grammars
    resources :kanjis
    resources :lesson_kanjis
    resources :videos
    resources :vocabularies
    resources :tests
    resources :questions
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :result

  scope :by_correct, ->{where is_correct: true}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons

  mount_uploader :image, ImageUploader

  validates :name, :description, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/grammar.rb
class Grammar < ApplicationRecord
  belongs_to :lesson

  validates :title, :content, presence: true

  scope :by_lesson, ->(lesson_id) {where lesson_id: lesson_id}
end

app/models/kanji.rb
class Kanji < ApplicationRecord
  extend ImportExportCSV
  belongs_to :lesson

  scope :by_lesson, ->id {where lesson_id: id}

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  attr_accessor :file_kanji, :file_voca

  belongs_to :category

  has_many :videos
  has_many :grammars
  has_many :vocabularies
  has_many :kanjis
  has_many :tests

  validates :name, :description, presence: true

  accepts_nested_attributes_for :kanjis, allow_destroy: true
  accepts_nested_attributes_for :vocabularies, allow_destroy: true

end

app/models/lesson_kanji.rb
class LessonKanji < ApplicationRecord
  belongs_to :lesson
  has_many :kanjis
end

app/models/lesson_vocabulary.rb
class LessonVocabulary < ApplicationRecord
  belongs_to :lesson
  belongs_to :vocabulary
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  belongs_to :result

  has_many :answers

  accepts_nested_attributes_for :answers, allow_destroy: true

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test

  has_many :question
  has_many :answer
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :lesson

  has_many :results
  has_many :questions

  scope :by_lesson, ->lesson_id {where lesson_id: lesson_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :result
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :lesson
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  extend ImportExportCSV

  belongs_to :lesson

  mount_uploader :image, ImageUploader
  mount_uploader :audio, SoundUploader

  scope :by_lesson, ->lesson_id {where lesson_id: lesson_id}
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController <  Admin::AdminController
  before_action :load_lesson, only: [:edit, :update, :destroy, :show]
  before_action :load_categories, only: [:new, :edit]

  def index
    @search_lesson = Lesson.all.order(:category_id).ransack(params[:q])
    @lessons = @search_lesson.result.page(params[:page]).per(Settings.paginate.medium_page)
  end

  def new
    @lesson = Lesson.new
    @lesson.kanjis.build
    respond_to do |format|
      format.js
    end
  end

  def create
    @lesson = Lesson.new lesson_params
    if @lesson.save
      Kanji.import_csv @lesson.id, lesson_params[:file_kanji] if lesson_params[:file_kanji].present?
      Vocabulary.import_csv @lesson.id, lesson_params[:file_voca] if lesson_params[:file_voca].present?

      add_message_flash(:success, t("admin.created"))
    else
      add_message_flash(:error, t("admin.failed"))
    end
    redirect_to admin_lessons_path
  end

  def edit
  end

  def update
    if @lesson.update_attributes lesson_params
      add_message_flash(:success, t("admin.updated"))
    else
      add_message_flash(:error, t("admin.failed"))
    end
  end

  def destroy
    if @lesson.destroy
      flash.now[:success] = t "admin.destroy"
    end
    respond_to do |format|
      format.json do
        render json:{
          flash: flash
        }
      end
    end
  end

  private
  def lesson_params
    params.require(:lesson).permit :name, :description, :category_id, :file_kanji, :file_voca,
      kanjis_attributes: [:id, :character, :vietnamese, :onyomi, :kunyomi, :example, :_destroy],
      vocabularies_attributes: [:id, :japanese, :vietnamese, :romaji, :audio, :image, :description, :_destroy]
  end

  def load_lesson
    @lesson = Lesson.find params[:id]
  end

  def load_categories
    @categories = Category.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def add_message_flash type, message
    flash[type] ||= []
    flash[type].push *message
  end

  def add_message_flash_now type, message
    flash.now[type] ||= []
    flash.now[type].push *message
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper
end

app/helpers/admin/tests_helper.rb
module Admin::TestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/admin/lessons/_modal_add_lesson.html.erb
<div class="modal fade addLessonAdmin" id="addLesson" tabindex="-1" role="dialog"
  aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modalAddlesson modal-lg ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"  data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          <%= t ".title" %>
        </h4>
      </div>
      <%= form_for [:admin, lesson], multipart: true do |f| %>
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-3">
              <label><%= t ".category" %></label>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <%= f.collection_select :category_id, categories, :id, :name, {prompt: false},
                  {class: "form-control"} %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-md-3">
                <label><%= t ".name" %></label>
              </div>
              <div class="col-md-8">
                <%= f.text_field :name, class: "form-control",  placeholder: t(".placeholder_name"), required: true %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-md-3">
                <label><%= t ".description" %></label>
              </div>
              <div class="col-md-8">
                <%= f.text_field :description, class: "form-control",  placeholder: t(".placeholder_description"), required: true %>
              </div>
            </div>
          </div>
        </div>
        <div class="card card-nav-tabs">
          <div class="card-header" data-background-color="blue">
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <span class="nav-tabs-title">Tasks:</span>
                <ul class="nav nav-tabs" data-tabs="tabs">
                  <li class="active">
                    <a href="#kanji" data-toggle="tab" aria-expanded="false">
                      <i class="material-icons">code</i>
                        Lesson kanji
                      <div class="ripple-container"></div></a>
                  </li>
                  <li class="">
                    <a href="#vocabulary" data-toggle="tab" aria-expanded="true">
                      <i class="material-icons">cloud</i>
                        Lesson vocabularies
                      <div class="ripple-container"></div></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="card-content modal-lesson-content">
            <div class="tab-content">
              <div class="tab-pane active" id="kanji">
                <div class="row importCSV">
                  <div class="checkbox col-md-1">
                    <label>
                      <input type="checkbox" name="optionsCheckboxes" id="checkboxImportKanji">
                      <span class="checkbox-material"><span class="check"></span></span>
                    </label>
                  </div>
                  <div class="col-md-2">
                    <%= f.file_field :file_kanji, accept: ".csv", class:"btn btn-info btn-xs button", title: "Upload file",
                      disabled: true, id: "importKanji" %>
                  </div>
                </div>
                <div class="lesson_kanji_form content-block-input-clones">
                  <div class="card input-form-kanji clone-item">
                    <div class="row">
                      <div class="col-md-1 pull-right">
                        <button type="button" rel="tooltip" title="" class="btn btn-danger btn-simple btn-xs remove-clone"
                          data-original-title="Remove" data-value="1">
                        <i class="material-icons">close</i>
                        <div class="ripple-container"></div></button>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group label-floating is-empty">
                          <label class="control-label"><%= t ".character" %></label>
                          <%= text_field_tag "lesson[kanjis_attributes][0][character]", nil, id:"kanji_character",
                            class: "form-control", required: true  %>
                          <span class="material-input"></span>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group label-floating is-empty">
                          <label class="control-label"><%= t ".vietnamese" %></label>
                          <%= text_field_tag "lesson[kanjis_attributes][0][vietnamese]", nil, id:"kanji_vietnamese",
                            class: "form-control" %>
                          <span class="material-input"></span>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group label-floating is-empty">
                          <label class="control-label"><%= t ".kunyomi" %></label>
                          <%= text_field_tag "lesson[kanjis_attributes][0][kunyomi]", nil, id:"kanji_kunyomi",
                            class: "form-control" %>
                          <span class="material-input"></span>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group label-floating is-empty">
                          <label class="control-label"><%= t ".onyomi" %></label>
                          <%= text_field_tag "lesson[kanjis_attributes][0][onyomi]", nil, id:"kanji_onyomi",
                            class: "form-control" %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group label-floating is-empty">
                          <label class="control-label"><%= t ".example" %></label>
                          <%= text_field_tag "lesson[kanjis_attributes][0][example]", nil, id:"kanji_example",
                            class: "form-control" %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <button type="button" class="btn btn-info btn-xs btn-add-lesson-kanji"
                  data-original-title="Add" ">
                  <i class="material-icons">add</i>
                <div class="ripple-container"></div></button>
              </div>
              <div class="tab-pane" id="vocabulary">
                <div class="row importCSVVoca">
                  <div class="checkbox col-md-1">
                    <label>
                      <input type="checkbox" name="optionsCheckboxes" id="checkboxImportVocabulary">
                      <span class="checkbox-material"><span class="check"></span></span>
                    </label>
                  </div>
                  <div class="col-md-2">
                    <%= f.file_field :file_voca, accept: ".csv", class:"btn btn-info btn-xs button", title: "Upload file",
                      disabled: true, id: "importVoca" %>
                  </div>
                </div>
                <div class="lesson_voca_form content-block-input-clones">
                  <div class="card input-form-voca clone-item">
                    <div class="row">
                      <div class="col-md-1 pull-right">
                        <button type="button" rel="tooltip" title="" class="btn btn-danger btn-simple btn-xs remove-clone"
                          data-original-title="Remove" data-value="1">
                        <i class="material-icons">close</i>
                        <div class="ripple-container"></div></button>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group label-floating is-empty">
                          <label class="control-label"><%= t ".character" %></label>
                          <%= text_field_tag "lesson[vocabularies_attributes][0][japanese]", nil, id:"voca_japanese",
                            class: "form-control" %>
                          <span class="material-input"></span>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group label-floating is-empty">
                          <label class="control-label"><%= t ".vietnamese" %></label>
                          <%= text_field_tag "lesson[vocabularies_attributes][0][vietnamese]", nil, id:"voca_vietnamese",
                            class: "form-control" %>
                          <span class="material-input"></span>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group label-floating is-empty">
                          <label class="control-label"><%= t ".romaji" %></label>
                          <%= text_field_tag "lesson[vocabularies_attributes][0][romaji]", nil, id:"voca_romaji",
                            class: "form-control" %>
                          <span class="material-input"></span>
                        </div>
                      </div>
                      <div class="col-md-3">
                        <label><%= t ".image" %></label>
                        <%= file_field_tag "lesson[vocabularies_attributes][0][image]", id:"voca_image", title: "Upload file" %>
                      </div>
                      <div class="col-md-3">
                        <label><%= t ".sound" %></label>
                        <%= file_field_tag "lesson[vocabularies_attributes][0][audio]", id:"voca_audio", title: "Upload file" %>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group label-floating is-empty">
                          <label class="control-label"><%= t ".description" %></label>
                          <%= text_field_tag "lesson[vocabularies_attributes][0][description]", nil, id:"voca_description",
                            class: "form-control" %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <button type="button" class="btn btn-info btn-xs btn-add-lesson-voca"
                  data-original-title="Add">
                  <i class="material-icons">add</i>
                <div class="ripple-container"></div></button>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">
            <%= t ".btn_close" %></button>
          <button type="submit" class="btn btn-info"><%= t ".btn_add_category" %></button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/lessons/_modal_update_lesson.html.erb
<div class="modal fade" id="updateLesson" tabindex="-1" role="dialog"
  aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"  data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          <%= t ".title" %>
        </h4>
      </div>
      <%= form_for [:admin, lesson], remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <label><%= t ".category" %></label>
            <div class="dropdown">
              <%= f.collection_select :category_id, categories, :id, :name, prompt: false,
                class: "btn btn-info dropdown-toggle caret" %>
            </div>
          </div>
          <div class="form-group">
            <label><%= t ".name" %></label>
            <%= f.text_field :name, class: "form-control",  placeholder: t(".placeholder_name"), required: true %>
          </div>
          <div class="form-group">
            <label><%= t ".description" %></label>
            <%= f.text_field :description, class: "form-control",  placeholder: t(".placeholder_description"), required: true %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">
            <%= t ".btn_close" %></button>
          <button type="submit" class="btn btn-info"><%= t ".btn_update_lesson" %></button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/lessons/_search_form.html.erb
<%= search_form_for @search_lesson, url: admin_lessons_path, id: "search-form navbar-right", class: "navbar-form" do |f| %>
  <div class="form-group  is-empty">
    <%= f.search_field :name_cont,
      class: "search-query form-control", placeholder: t(".search") %>
  </div>
  <%= button_tag type: "submit", class: "btn btn-white btn-round btn-just-icon" do %>
    <i class="material-icons">search</i><div class="ripple-container"></div>
  <% end %>
<% end %>

app/views/admin/lessons/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header" data-background-color="orange">
            <i class="material-icons">assignment</i>
            <p class="category">grammar</p>
          </div>
          <div class="card-content">
            <h3 class="title">
              <%= @lesson.grammars.size %><small>grammars</small></h3>
              <%= link_to "Add New Grammar", new_admin_grammar_path(lesson_id: @lesson.id), class:"btn btn-success" %>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons text-danger">warning</i>
              <%= link_to "Get more details", admin_grammars_path %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header" data-background-color="green">
            <i class="material-icons">ondemand_video</i>
            <p class="category">Video</p>
          </div>
          <div class="card-content">
            <h3 class="title">
              <%= @lesson.videos.size %><small>video</small></h3>
              <%= link_to "Add New Video", new_admin_video_path(lesson_id: @lesson.id), class:"btn btn-success" %>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">date_range</i>
              <%= link_to "Get more details", admin_videos_path(lesson_id: @lesson.id) %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header" data-background-color="red">
            <i class="material-icons">translate </i>
            <p class="category">Kanji</p>
          </div>
          <div class="card-content">
            <h3 class="title">
              <%= @lesson.kanjis.size %><small>Kanji</small></h3>
              <%= link_to "Add New Kanji", new_admin_kanji_path(lesson_id: @lesson.id), class:"btn btn-success", remote: true %>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">local_offer</i>
              <%= link_to "Get more details", admin_kanjis_path(lesson_id: @lesson.id) %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header" data-background-color="blue">
            <i class="material-icons">import_contacts</i>
            <p class="category">vocabulary</p>
          </div>
          <div class="card-content">
            <h3 class="title">
              <%= @lesson.vocabularies.size %><small>vocabularies</small></h3>
              <%= link_to "Add New Kanji", new_admin_vocabulary_path(lesson_id: @lesson.id), class:"btn btn-success", remote: true %>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">update</i>
              <%= link_to "Get more details", admin_vocabularies_path(lesson_id: @lesson.id) %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header" data-background-color="blue">
            <i class="material-icons">question_answer</i>
            <p class="category">vocabulary</p>
          </div>
          <div class="card-content">
            <h3 class="title">
              <%= @lesson.tests.size %><small>Tests</small></h3>
              <%= link_to "Add New Kanji", new_admin_test_path(lesson_id: @lesson.id), class:"btn btn-success", remote: true %>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">update</i>
              <%= link_to "Get more details", admin_tests_path(lesson_id: @lesson.id) %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="card">
        <div class="card-header" data-background-color="blue">
          <h4 class="title">Edit Lesson</h4>
        </div>
        <div class="card-content">
          <%= form_for [:admin, @lesson] do |f| %>
            <div class="row">
              <div class="col-md-3">
                <label><%= t ".category" %></label>
              </div>
              <div class="col-md-8">
                <div class="dropdown">
                  <%= f.collection_select :category_id, @categories, :id, :name, prompt: false,
                  class: "btn btn-info dropdown-toggle caret" %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-md-3">
                  <label><%= t ".name" %></label>
                </div>
                <div class="col-md-8">
                  <%= f.text_field :name, class: "form-control",  placeholder: t(".placeholder_name"), required: true %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-md-3">
                  <label><%= t ".description" %></label>
                </div>
                <div class="col-md-8">
                  <%= f.text_field :description, class: "form-control",  placeholder: t(".placeholder_description"), required: true %>
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-success pull-right"><%= t ".btn_update_lesson" %></button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/lessons/edit.js.erb
$("section.modal-content").html(
  "<%= j render "modal_update_lesson", lesson: @lesson, categories: @categories %>");
$("#updateLesson").modal("show");

app/views/admin/lessons/index.html.erb
<div class="content">
  <%= render "layouts/flash", flash: flash %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card card-nav-tabs">
            <div class="card-header" data-background-color="blue">
              <div class="nav-tabs-navigation">
                <div class="nav-tabs-wrapper">
                  <span class="nav-tabs-title">Table:</span>
                  <ul class="nav nav-tabs" data-tabs="tabs">
                    <li class="active pull-right">
                      <%= link_to new_admin_lesson_path, data: {original_title: "New"}, remote: true  do %>
                        <i class="material-icons">bug_report</i>
                        <%= t ".btn_add_lesson" %>
                      <div class="ripple-container"></div>
                      <% end %>
                    </li>
                    <li class="">
                      <i class="material-icons">list</i>
                        <%= t ".list_lesson" %>
                      <div class="ripple-container"></div></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="pull-right">
              <%= render "search_form" %>
            </div>
          </div>
          <div class="card-content table-responsive">
            <table class="table table-hover">
              <thead class="text-center">
                <th><%= t ".id" %></th>
                <th>
                  <%= sort_link @search_lesson, :category_id, t(".category") %>
                </th>
                <th>
                  <%= sort_link @search_lesson, :name, t(".name") %>
                </th>
                <th><%= t ".description" %></th>
                <th>
                  <%= sort_link @search_lesson, :name, t(".created_at") %>
                </th>
                <th class="text-center"><%= t ".action" %></th>
              </thead>
              <tbody>
                <% @lessons.each_with_index do |lesson, index| %>
                  <tr id="lesson-<%= lesson.id %>">
                    <td><%= index + 1 %></td>
                    <td><%= lesson.category&.name %></td>
                    <td><%= lesson.name %></td>
                    <td><%= lesson.description %></td>
                    <td><%= lesson.created_at.strftime("%m/%d/%Y") %></td>
                    <td class="text-center">
                      <%= link_to edit_admin_lesson_path(lesson), class: "btn btn-info btn-simple btn-xs",
                        data: {original_title: "Edit"} do %>
                        <i class="material-icons info">edit</i>
                      <% end %>
                      <button type="button" rel="tooltip" title="" class="btn btn-danger btn-simple btn-xs btn-delete-lesson"
                        data-original-title="Remove" data-value="<%= lesson.id %>">
                        <i class="material-icons">close</i>
                      <div class="ripple-container"></div></button>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= paginate @lessons %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/lessons/new.js.erb
$("section.modal-content").html(
  "<%= j render "modal_add_lesson", lesson: @lesson, categories: @categories %>");
$("#addLesson").modal("show");
cloneLessonKanji();
cloneLessonVoca();
checkBoxEvent();