config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "static_page#home"

  namespace :admin do
    resources :categories
    resources :lessons
    resources :grammars
    resources :kanjis
    resources :lesson_kanjis
    resources :videos
    resources :vocabularies
    resources :tests
    resources :questions
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :result

  scope :by_correct, ->{where is_correct: true}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons

  mount_uploader :image, ImageUploader

  validates :name, :description, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/grammar.rb
class Grammar < ApplicationRecord
  belongs_to :lesson

  validates :title, :content, presence: true

  scope :by_lesson, ->(lesson_id) {where lesson_id: lesson_id}
end

app/models/kanji.rb
class Kanji < ApplicationRecord
  extend ImportExportCSV
  belongs_to :lesson

  scope :by_lesson, ->id {where lesson_id: id}

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  attr_accessor :file_kanji, :file_voca

  belongs_to :category

  has_many :videos
  has_many :grammars
  has_many :vocabularies
  has_many :kanjis
  has_many :tests

  validates :name, :description, presence: true

  accepts_nested_attributes_for :kanjis, allow_destroy: true
  accepts_nested_attributes_for :vocabularies, allow_destroy: true

end

app/models/lesson_kanji.rb
class LessonKanji < ApplicationRecord
  belongs_to :lesson
  has_many :kanjis
end

app/models/lesson_vocabulary.rb
class LessonVocabulary < ApplicationRecord
  belongs_to :lesson
  belongs_to :vocabulary
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  belongs_to :result

  has_many :answers

  accepts_nested_attributes_for :answers, allow_destroy: true

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test

  has_many :question
  has_many :answer
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :lesson

  has_many :results
  has_many :questions

  scope :by_lesson, ->lesson_id {where lesson_id: lesson_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :result
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :lesson
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  extend ImportExportCSV

  belongs_to :lesson

  mount_uploader :image, ImageUploader
  mount_uploader :audio, SoundUploader

  scope :by_lesson, ->lesson_id {where lesson_id: lesson_id}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :load_category, only: [:edit, :update, :destroy]
  def index
    @search_category = Category.ransack params[:q]
    @categories = @search_category.result.page(params[:page]).per(Settings.paginate.medium_page)
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @category = Category.new category_params
    if @category.save
      add_message_flash(:success, t("admin.created"))
    else
      add_message_flash(:error, t("admin.failed"))
    end
    redirect_to :back
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @category.update_attributes category_params
      add_message_flash(:success, t("admin.updated"))
    else
      add_message_flash(:error, t("admin.failed"))
    end
    redirect_to :back
  end

  def destroy
    if @category.destroy
      flash.now[:success] = t "admin.destroy"
    end
    respond_to do |format|
      format.json do
        render json:{
          flash: flash
        }
      end
    end
  end

  private
  def category_params
    params.require(:category).permit :name, :description, :image
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def add_message_flash type, message
    flash[type] ||= []
    flash[type].push *message
  end

  def add_message_flash_now type, message
    flash.now[type] ||= []
    flash.now[type].push *message
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/admin/tests_helper.rb
module Admin::TestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/admin/categories/_modal_add_category.html.erb
<div class="modal fade" id="addCategory" tabindex="-1" role="dialog"
  aria-labelledby="myModalLabel" aria-hidden="true">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"  data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          <%= t ".title" %>
        </h4>
      </div>
      <%= form_for [:admin, category], multipart: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <label><%= t ".name" %></label>
            <%= f.text_field :name, class: "form-control",  placeholder: t(".placeholder_name"), required: true %>
          </div>
          <div class="">
            <label><%= t ".image" %></label>
            <%= f.file_field :image, title: "Upload file"  %>
          </div>
          <div class="form-group">
            <label><%= t ".description" %></label>
            <%= f.text_field :description, class: "form-control",  placeholder: t(".placeholder_description"), required: true %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">
            <%= t ".btn_close" %></button>
          <button type="submit" class="btn btn-info"><%= t ".btn_add_category" %></button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/_modal_update_category.html.erb
<div class="modal fade" id="updateCategory" tabindex="-1" role="dialog"
  aria-labelledby="myModalLabel" aria-hidden="true">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"  data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          <%= t ".title" %>
        </h4>
      </div>
      <%= form_for [:admin, category], multipart: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <label><%= t ".name" %></label>
            <%= f.text_field :name, class: "form-control",  placeholder: t(".placeholder_name"), required: true %>
          </div>
          <div class="">
            <label><%= t ".image" %></label>
            <%= f.file_field :image, title: "Upload file"  %>
          </div>
          <div class="form-group">
            <label><%= t ".description" %></label>
            <%= f.text_field :description, class: "form-control",  placeholder: t(".placeholder_description"), required: true %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">
            <%= t ".btn_close" %></button>
          <button type="submit" class="btn btn-info"><%= t ".btn_update_category" %></button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/_search_form.html.erb
<%= search_form_for @search_category, url: admin_categories_path, id: "search-form navbar-right", class: "navbar-form" do |f| %>
  <div class="form-group  is-empty">
    <%= f.search_field :name_cont,
      class: "search-query form-control", placeholder: t(".search") %>
  </div>
  <%= button_tag type: "submit", class: "btn btn-white btn-round btn-just-icon" do %>
    <i class="material-icons">search</i><div class="ripple-container"></div>
  <% end %>
<% end %>

app/views/admin/categories/edit.js.erb
$("section.modal-content").html(
  "<%= j render "modal_update_category", category: @category %>");
$("#updateCategory").modal("show");

app/views/admin/categories/index.html.erb
<div class="content">
  <%= render "layouts/flash", flash: flash %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card card-nav-tabs">
            <div class="card-header" data-background-color="blue">
              <div class="nav-tabs-navigation">
                <div class="nav-tabs-wrapper">
                  <span class="nav-tabs-title">Table:</span>
                  <ul class="nav nav-tabs" data-tabs="tabs">
                    <li class="active pull-right">
                      <%= link_to new_admin_category_path, data: {original_title: "New"}, remote: true do %>
                        <i class="material-icons">bug_report</i>
                        <%= t ".btn_add_category" %>
                      <div class="ripple-container"></div>
                      <% end %>
                   </li>
                    <li class="">
                      <i class="material-icons">list</i>
                        <%= t ".list_category" %>
                      <div class="ripple-container"></div></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="pull-right">
              <%= render "search_form" %>
            </div>
          </div>
          <div class="card-content table-responsive">
            <table class="table table-hover">
              <thead class="text-center">
                <th><%= t ".id" %></th>
                <th>
                  <%= sort_link @search_category, :name, t(".name") %>
                </th>
                <th><%= t ".description" %></th>
                <th>
                  <%= sort_link @search_category, :created_at, t(".created_at") %>
                </th>
                <th><%= t ".action" %></th>
              </thead>
              <tbody>
                <% @categories.each_with_index do |category, index| %>
                  <tr id="category-<%= category.id %>">
                    <td><%= index + 1 %></td>
                    <td><%= category.name %></td>
                    <td><%= category.description %></td>
                    <td><%= category.created_at.strftime("%m/%d/%Y") %></td>

                    <td class="text-center">
                      <%= link_to edit_admin_category_path(category), class: "btn btn-info btn-simple btn-xs",
                        data: {original_title: "Edit"}, remote: true do %>
                        <i class="material-icons info">edit</i>
                      <% end %>
                      <button type="button" rel="tooltip" title="" class="btn-delete-category btn btn-danger btn-simple btn-xs"
                        data-original-title="Remove" data-value="<%= category.id %>">
                        <i class="material-icons">close</i>
                      <div class="ripple-container"></div></button>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= paginate @categories %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.js.erb
$("section.modal-content").html(
  "<%= j render "modal_add_category", category: @category %>");
$("#addCategory").modal("show");