config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "static_page#home"

  namespace :admin do
    resources :categories
    resources :lessons
    resources :grammars
    resources :kanjis
    resources :lesson_kanjis
    resources :videos
    resources :vocabularies
    resources :tests
    resources :questions
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :result

  scope :by_correct, ->{where is_correct: true}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons

  mount_uploader :image, ImageUploader

  validates :name, :description, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/grammar.rb
class Grammar < ApplicationRecord
  belongs_to :lesson

  validates :title, :content, presence: true

  scope :by_lesson, ->(lesson_id) {where lesson_id: lesson_id}
end

app/models/kanji.rb
class Kanji < ApplicationRecord
  extend ImportExportCSV
  belongs_to :lesson

  scope :by_lesson, ->id {where lesson_id: id}

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  attr_accessor :file_kanji, :file_voca

  belongs_to :category

  has_many :videos
  has_many :grammars
  has_many :vocabularies
  has_many :kanjis
  has_many :tests

  validates :name, :description, presence: true

  accepts_nested_attributes_for :kanjis, allow_destroy: true
  accepts_nested_attributes_for :vocabularies, allow_destroy: true

end

app/models/lesson_kanji.rb
class LessonKanji < ApplicationRecord
  belongs_to :lesson
  has_many :kanjis
end

app/models/lesson_vocabulary.rb
class LessonVocabulary < ApplicationRecord
  belongs_to :lesson
  belongs_to :vocabulary
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  belongs_to :result

  has_many :answers

  accepts_nested_attributes_for :answers, allow_destroy: true

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test

  has_many :question
  has_many :answer
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :lesson

  has_many :results
  has_many :questions

  scope :by_lesson, ->lesson_id {where lesson_id: lesson_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :result
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :lesson
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  extend ImportExportCSV

  belongs_to :lesson

  mount_uploader :image, ImageUploader
  mount_uploader :audio, SoundUploader

  scope :by_lesson, ->lesson_id {where lesson_id: lesson_id}
end

app/controllers/admin/grammars_controller.rb
class Admin::GrammarsController < Admin::AdminController
  before_action :load_lessons, only: [:new, :edit]
  before_action :load_grammar, only: [:show, :edit, :update, :destroy]

  def index
    @grammars = params[:lesson_id].present? ? Grammar.by_lesson(params[:lesson_id]) : Grammar.all
  end

  def new
    @grammar = Grammar.new
  end

  def show
  end

  def create
    @grammar = Grammar.new grammar_params
    if @grammar.save
      add_message_flash(:success, t("admin.created"))
    else
      add_message_flash(:error, t("admin.failed"))
    end
    redirect_to admin_grammars_path
  end

  def update
    if @grammar.update_attributes grammar_params
      add_message_flash(:success, t("admin.updated"))
    else
      add_message_flash(:error, t("admin.failed"))
    end
    redirect_to admin_grammars_path
  end

  def destroy
    if @grammar.destroy
      flash.now[:success] = t "admin.destroy"
    end
    respond_to do |format|
      format.json do
        render json:{
          flash: flash
        }
      end
    end
  end

  private
  def grammar_params
    params.require(:grammar).permit :title, :lesson_id, :content
  end

  def load_grammar
    @grammar = Grammar.find params[:id]
  end

  def load_lessons
    @lessons = Lesson.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def add_message_flash type, message
    flash[type] ||= []
    flash[type].push *message
  end

  def add_message_flash_now type, message
    flash.now[type] ||= []
    flash.now[type].push *message
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/admin/grammars_helper.rb
module Admin::GrammarsHelper
end

app/helpers/admin/tests_helper.rb
module Admin::TestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/admin/grammars/_form.html.erb
<%= form_for [:admin, @grammar] do |f| %>
  <div class="card-content">
    <div id="typography">
      <div class="form-group">
        <label>title</label>
        <%= f.text_field :title, class: "form-control",  placeholder: t(".title"), required: true %>
        <span class="material-input"></span>
      </div>
    </div>
    <div>
      <%= f.hidden_field :lesson_id, value: 1 %>
      <%= f.label :content %><br>
      <%= f.text_area :content, class: "ckeditor" %>
    </div>
    <button class="btn btn-success pull-right"><%= t ".btn_submit" %></button>
  </div>
<% end %>

app/views/admin/grammars/edit.html.erb
<div class="content">
  <%= render "layouts/flash", flash: flash %>
  <div class="container-fluid">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="blue">
          <h4 class="title"><%= t ".title" %></h4>
          <p class="category"></p>
        </div>
        <%= form_for [:admin, @grammar] do |f| %>
          <div class="card-content">
            <div id="typography">
              <div class="form-group">
                <label>title</label>
                <%= f.text_field :title, class: "form-control",  placeholder: t(".title"), required: true %>
                <span class="material-input"></span>
              </div>
            </div>
            <div>
              <%= f.label :content %><br>
              <%= f.text_area :content, class: "ckeditor" %>
            </div>
            <button class="btn btn-success pull-right"><%= t ".btn_submit" %></button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/grammars/index.html.erb
<div class="content">
  <%= render "layouts/flash", flash: flash %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card card-nav-tabs">
            <div class="card-header" data-background-color="blue">
              <div class="nav-tabs-navigation">
                <div class="nav-tabs-wrapper">
                  <span class="nav-tabs-title">Table:</span>
                  <ul class="nav nav-tabs" data-tabs="tabs">
                    <li class="active pull-right">
                      <%= link_to new_admin_grammar_path, data: {original_title: "New"} do %>
                        <i class="material-icons">bug_report</i>
                        <%= t ".btn_add" %>
                      <div class="ripple-container"></div>
                      <% end %>
                   </li>
                    <li class="">
                      <i class="material-icons">list</i>
                        <%= t ".title" %>
                      <div class="ripple-container"></div></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="card-content table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th><%= t ".id" %></th>
                  <th><%= t ".image" %></th>
                  <th><%= t ".lesson" %></th>
                  <th><%= t ".title_grammar" %></th>
                  <th><%= t ".created_at" %></th>
                  <th><%= t ".action" %></th>
                </tr>
              </thead>
              <tbody>
                <% @grammars.each_with_index do |grammar, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td class="td-image">
                      <div class="img-container">
                        <%= image_tag "blog-1.jpg" %>
                      </div>
                    </td>
                    <td>
                      <%= grammar.lesson&.name %>
                    </td>
                    <td>
                      <%= grammar.title %>
                    </td>
                    <td>
                      <%= grammar.created_at.strftime("%F") %>
                    </td>
                    <td class="td-actions text-center">
                      <%= link_to admin_grammar_path(grammar), class:"btn btn-info btn-simple btn-icon",
                        data: {original_title: "View"} do %>
                        <i class="fa fa-image"></i>
                      <% end %>
                      <%= link_to edit_admin_grammar_path(grammar), class:"btn btn-success btn-simple btn-icon",
                        data: {original_title: "Edit"} do %>
                        <i class="fa fa-edit"></i>
                      <% end %>
                      <button type="button" rel="tooltip" data-placement="left" data-value="<%= grammar.id %>"
                        class="btn btn-danger btn-simple btn-icon " id="btn-delete-gramar" data-original-title="Remove">
                        <i class="fa fa-times"></i>
                      </button>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/grammars/new.html.erb
<div class="content">
  <%= render "layouts/flash", flash: flash %>
  <div class="container-fluid">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header" data-background-color="blue">
          <h4 class="title"><%= t ".title" %></h4>
          <p class="category"></p>
        </div>
        <%= form_for [:admin, @grammar] do |f| %>
          <div class="card-content">
            <div id="typography">
              <div class="form-group">
                <label>title</label>
                <%= f.text_field :title, class: "form-control",  placeholder: t(".title"), required: true %>
                <span class="material-input"></span>
              </div>
            </div>
            <div>
              <%= f.hidden_field :lesson_id, value: params[:lesson_id] %>
              <%= f.label :content %><br>
              <%= f.text_area :content, class: "ckeditor" %>
            </div>
            <button class="btn btn-success pull-right"><%= t ".btn_submit" %></button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/grammars/show.html.erb
<div class="content">
  <%= render "layouts/flash", flash: flash %>
  <div class="container-fluid">
    <div class="tim-typo">
      <h1>
        <%= @grammar.lesson&.name %>
      </h1>
    </div>
    <h3>
      <%= @grammar.title %>
    </h3>
    <%= @grammar.content.html_safe %>
  </div>
</div>