config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "static_page#home"

  namespace :admin do
    resources :categories
    resources :lessons
    resources :grammars
    resources :kanjis
    resources :lesson_kanjis
    resources :videos
    resources :vocabularies
    resources :tests
    resources :questions
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :result

  scope :by_correct, ->{where is_correct: true}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons

  mount_uploader :image, ImageUploader

  validates :name, :description, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/grammar.rb
class Grammar < ApplicationRecord
  belongs_to :lesson

  validates :title, :content, presence: true

  scope :by_lesson, ->(lesson_id) {where lesson_id: lesson_id}
end

app/models/kanji.rb
class Kanji < ApplicationRecord
  extend ImportExportCSV
  belongs_to :lesson

  scope :by_lesson, ->id {where lesson_id: id}

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  attr_accessor :file_kanji, :file_voca

  belongs_to :category

  has_many :videos
  has_many :grammars
  has_many :vocabularies
  has_many :kanjis
  has_many :tests

  validates :name, :description, presence: true

  accepts_nested_attributes_for :kanjis, allow_destroy: true
  accepts_nested_attributes_for :vocabularies, allow_destroy: true

end

app/models/lesson_kanji.rb
class LessonKanji < ApplicationRecord
  belongs_to :lesson
  has_many :kanjis
end

app/models/lesson_vocabulary.rb
class LessonVocabulary < ApplicationRecord
  belongs_to :lesson
  belongs_to :vocabulary
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  belongs_to :result

  has_many :answers

  accepts_nested_attributes_for :answers, allow_destroy: true

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test

  has_many :question
  has_many :answer
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :lesson

  has_many :results
  has_many :questions

  scope :by_lesson, ->lesson_id {where lesson_id: lesson_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :result
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :lesson
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  extend ImportExportCSV

  belongs_to :lesson

  mount_uploader :image, ImageUploader
  mount_uploader :audio, SoundUploader

  scope :by_lesson, ->lesson_id {where lesson_id: lesson_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def add_message_flash type, message
    flash[type] ||= []
    flash[type].push *message
  end

  def add_message_flash_now type, message
    flash.now[type] ||= []
    flash.now[type].push *message
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/layouts/_flash.html.erb
<div id="flash-messages">
  <% if flash[:error]&.any? %>
    <% flash[:error].each do |message| %>
      <div class="alert alert-danger" id="flash-messages-error">
        <button type="button" aria-hidden="true" class="close" id="closeFlash">×</button>
        <span><b> Errors: </b><%= message %></span>
      </div>
    <% end %>
  <% end %>
  <% if flash[:success]&.any? %>
    <% flash[:success].each do |message| %>
      <div class="alert alert-success" id="flash-messages-success">
        <button type="button" aria-hidden="true" class="close" id="closeFlash">×</button>
        <span><b> Success: </b><%= message %></span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_footer_admin.html.erb
<footer class="footer">
  <div class="container-fluid">
    <nav class="pull-left">
      <ul>
        <li>
          <a href="#">
            <%= t ".home" %>
          </a>
        </li>
        <li>
          <a href="#">
            <%= t ".company" %>
          </a>
        </li>
        <li>
          <a href="#">
            <%= t ".blog" %>
          </a>
        </li>
      </ul>
    </nav>
    <p class="copyright pull-right">
      &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com"></a>
    </p>
  </div>
</footer>

app/views/layouts/_footer_user.html.erb
<footer class="footer">
  <div class="container">
    <nav class="pull-left">
      <ul>
        <li>
          <a href="http://www.creative-tim.com">
            Creative Tim
          </a>
        </li>
        <li>
          <a href="http://presentation.creative-tim.com">
           About Us
         </a>
       </li>
       <li>
        <a href="http://blog.creative-tim.com">
         Blog
       </a>
     </li>
     <li>
      <a href="http://www.creative-tim.com/license">
        Licenses
      </a>
    </li>
  </ul>
</nav>
<div class="copyright pull-right">
  &copy; 2016, made with <i class="material-icons">favorite</i> by Creative Tim for a better web.
</div>
</div>
</footer>

app/views/layouts/_header_admin.html.erb
<div class="sidebar" data-color="blue" data-image="">
<div class="logo">
  <a href="http://www.creative-tim.com" class="simple-text">
    Creative Tim
  </a>
</div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="active">
        <%= link_to admin_lessons_path, data: {original_title: "Dashboard"} do %>
          <i class="material-icons info">dashboard</i>
            <p>Dashboard</p>
        <% end %>
      </li>
      <li>
          <a href="#">
              <i class="material-icons">person</i>
              <p>User Profile</p>
          </a>
      </li>
      <li>
        <%= link_to admin_categories_path, data: {original_title: "Categories"} do %>
          <i class="material-icons">content_paste</i>
          <p>Categories</p>
        <% end %>
      </li>
      <li>
        <%= link_to admin_lessons_path, data: {original_title: "Lesson"} do %>
          <i class="material-icons info">dashboard</i>
          <p>Lesson</p>
        <% end %>
      </li>
      <li>
        <%= link_to admin_grammars_path, data: {original_title: "Grammars"} do %>
          <i class="material-icons">content_paste</i>
          <p>Grammars</p>
        <% end %>
      </li>
      <li>
        <%= link_to admin_kanjis_path, data: {original_title: "Kanjis"} do %>
          <i class="material-icons info">dashboard</i>
          <p>Kanjis</p>
        <% end %>
      </li>
      <li>
        <%= link_to admin_vocabularies_path, data: {original_title: "Vocabularies"} do %>
          <i class="material-icons info">dashboard</i>
          <p>Vocabularies</p>
        <% end %>
      </li>
      <li>
        <%= link_to admin_tests_path, data: {original_title: "Tests"} do %>
          <i class="material-icons info">dashboard</i>
          <p>Tests</p>
        <% end %>
      </li>
      <li>
          <a href="#">
              <i class="material-icons text-gray">notifications</i>
              <p>Notifications</p>
          </a>
      </li>
      <li class="active-pro">
          <a href="#">
              <i class="material-icons">unarchive</i>
              <p>Upgrade to PRO</p>
          </a>
      </li>
    </ul>
  </div>
</div>

<div class="main-panel">
<nav class="navbar navbar-transparent navbar-absolute">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Material Dashboard</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
            <i class="material-icons">dashboard</i>
            <p class="hidden-lg hidden-md">Dashboard</p>
          </a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="material-icons">notifications</i>
            <span class="notification">5</span>
            <p class="hidden-lg hidden-md">Notifications</p>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">Mike John responded to your email</a></li>
            <li><a href="#">You have 5 new tasks</a></li>
            <li><a href="#">You're now friend with Andrew</a></li>
            <li><a href="#">Another Notification</a></li>
            <li><a href="#">Another One</a></li>
          </ul>
        </li>
        <li>
          <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
             <i class="material-icons">person</i>
             <p class="hidden-lg hidden-md">Profile</p>
          </a>
        </li>
      </ul>

      <form class="navbar-form navbar-right" role="search">
        <div class="form-group  is-empty">
          <input type="text" class="form-control" placeholder="Search">
          <span class="material-input"></span>
        </div>
        <button type="submit" class="btn btn-white btn-round btn-just-icon">
          <i class="material-icons">search</i><div class="ripple-container"></div>
        </button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_header_user.html.erb
<nav class="navbar navbar-transparent navbar-fixed-top navbar-color-on-scroll">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="http://www.creative-tim.com">
        <div class="logo-container">
          <div class="logo">
          <img src="/assets/new_logo.png" alt="Creative Tim Logo" rel="tooltip" title="<b>Material Kit</b> was Designed & Coded with care by the staff from <b>Creative Tim</b>" data-placement="bottom" data-html="true">
          </div>
          <div class="">
            Nihongo
          </div>
        </div>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="navigation-index">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown dropdown-categories" data-no-turbolink="">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <i class="material-icons">apps</i>Chủ đề
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="/bootstrap-themes">
                All Categories
              </a>
            </li>
            <li>
              <a href="/bootstrap-themes/admin-dashboard">
                Admin &amp; Dashboards
              </a>
            </li>
          </ul>
        </li>
        <li class="dropdown dropdown-categories" data-no-turbolink="">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <i class="material-icons">dashboard</i>Các bảng chữ cái
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="/bootstrap-themes">
                All Categories
              </a>
            </li>
            <li>
              <a href="/bootstrap-themes/admin-dashboard">
                Admin &amp; Dashboards
              </a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" target="_blank">
            <i class="material-icons">translate</i>Kanjis
          </a>
        </li>
        <li>
          <a href="#" target="_blank">
            <i class="material-icons">assignment</i> Bài Test
          </a>
        </li>
        <li>
          <a rel="tooltip" title="Like us on Facebook" data-placement="bottom" href="https://www.facebook.com/CreativeTim" target="_blank" class="btn btn-white btn-simple btn-just-icon">
            <i class="fa fa-facebook-square"></i>
          </a>
        </li>
        <li>
          <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
             <i class="material-icons">person</i>
             <p class="hidden-lg hidden-md">Profile</p>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="">
  <div class="header header-filter" style="background-image: url(<%= asset_path 'cover-header.jpg' %>);">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="brand-text-heder">
            <h2>Cùng nhau học tiếng Nhật.</h2>
            <h3>web học tiếng Nhật trực tuyến</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons" %>

    <%= javascript_include_tag "application" %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div class="wrapper">
      <%= render "layouts/header_admin" %>
      <%= yield %>
      <%= render "layouts/footer_admin" %>
    </div>
    <section class="modal-content"></section>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons" %>

    <%= javascript_include_tag "application" %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body class="index-page">
    <%= render "layouts/header_user" %>
      <%= yield %>
      <%= render "layouts/footer_user" %>
    <section class="modal-content"></section>
  </body>
</html>